function(enable_doxygen)
  option(ENABLE_DOC "Enable doc builds of source" OFF)
  if(ENABLE_DOC)
    set(DOXYGEN_CALLER_GRAPH YES)
    set(DOXYGEN_CALL_GRAPH YES)
    set(DOXYGEN_EXTRACT_ALL YES)
    find_package(Doxygen REQUIRED)
  endif()
endfunction()
